# Configuration for the blockchain connection and settings
BASE_TESTNET_PROVIDER = 'https://sepolia.base.org'
EVENT_CONTRACT_ADDRESS = '0xYOUR_EVENT_CONTRACT_ADDRESS'
AGREEMENT_CONTRACT_ADDRESS = '0xYOUR_AGREEMENT_CONTRACT_ADDRESS'
